name: Update README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Ersetze '3.x' durch die gewünschte Python-Version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install svgwrite requests

      - name: Generate GitHub Readme Stats
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        run: |
          python generate_svg.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add top-langs.svg
          git commit -m 'Update top languages in README' || echo "No changes to commit"
          git push
